version: '2'
services:
  # git:
  #   image: unixtastic/git-ssh-server
  #   ports:
  #   # - "443:443"
  #   - "2222:22"
  #   volumes:
  #   - .:/code
  #   container_name: git
  ci:
    image: jenkins:2.7.2
    links:
    - ansible
    ports:
    - "8080:8080"
    container_name: ci
  ansible:
    build: ansible/.
    links:
    # - git
    # - load
    - front
    - zabbixserver
    - zabbixweb
    - backend
    # image: ansible/centos7-ansible
    # volumes:
    # - playbook:/playbook
    command: tail -F /var/log/test
    container_name: ansible
  front:
    build: centos6_with_ssh/.
    links: 
    - zabbixserver
    - zabbixweb
    expose:
    - "22"
    ports:
    - "80:80"
    container_name: front
  zabbixserver:
    build: centos6_with_ssh/.
    links: 
    - backend
    expose:
    - "22"
    container_name: zabbixserver
    # command: tail -F /var/log/test
  zabbixweb:
    build: centos6_with_ssh/.
    links: 
    - backend
    expose:
    - "22"
    - "8081"
    ports:
    - "8081:8081"
    container_name: zabbixweb
    # command: tail -F /var/log/test
  backend:
    build: centos6_with_ssh/.
    expose:
    - "22"
    - "3306"
    ports:
    - "3306:3306"
    container_name: backend
    # command: tail -F /var/log/test
# volumes:
#   playbook:
#     external: true