version: '2'
services:
  # ci:
  #   image: jenkins:2.7.2
  #   links:
  #   - ansible
  #   ports:
  #   - "8080:8080"
  #   container_name: ci
  ansible:
    build: ansible/.
    links:
    - front
    - zabbixserver
    - backend
    command: tail -F /var/log/test
    container_name: ansible
  front:
    build: centos6_with_ssh/.
    links: 
    - zabbixserver
    expose:
    - "22"
    ports:
    - "80:80"
    container_name: front
  zabbixserver:
    build: centos6_with_ssh/.
    links: 
    - backend
    expose:
    - "22"
    - "80"
    ports:
    - "8081:80"
    container_name: zabbixserver
    # command: tail -F /var/log/test
  backend:
    build: centos6_with_ssh/.
    expose:
    - "22"
    - "3306"
    ports:
    - "3306:3306"
    container_name: backend
    # command: tail -F /var/log/test
# volumes:
#   playbook:
#     external: true